#!/bin/bash

echo "========================================="
echo "🚀 OCR Application - GitHub Codespaces"
echo "========================================="
echo ""
echo "✅ Environment ready!"
echo "✅ Tesseract OCR installed"
echo "✅ Python dependencies installed"
echo ""
echo "📋 Available commands:"
echo "   python main.py              # Run GUI application"
echo "   python cli_app.py --help    # Run CLI version"
echo "   python test_ocr.py          # Run tests"
echo ""
echo "📁 Your files are in: /workspaces/OCR-Project"
echo ""
echo "🎯 Quick start:"
echo "   python main.py"
echo ""